### ISSUE TITLE
[Epic] #inc-517 Followups

### ISSUE THREAD

**Issue by kahest** [getsentry/sentry-native#961]
Technical context is available here: https://github.com/getsentry/team-processing-private/issues/38

```[tasklist]
### [P1] Post Mortem action items
- [ ] https://github.com/getsentry/sentry-native/issues/959
- [ ] https://github.com/getsentry/sentry-native/issues/960
```

```[tasklist]
### \[P2] Post Mortem action items
- [ ] https://github.com/getsentry/sentry/issues/66418
- [ ] https://github.com/getsentry/sentry-java/pull/3189
- [ ] https://github.com/getsentry/sentry-native/pull/944
```

```[tasklist]
### Later/optional/TBD
- [ ] https://github.com/getsentry/sentry-native/issues/962
- [ ] https://github.com/getsentry/sentry-native/issues/997
- [ ] https://github.com/getsentry/sentry-native/issues/987
```

**Comment by kahest** [comment]
all non-optional items have been completed - closing now
